dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
    #- curl -L -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -L -o docker-build https://github.com/yetist/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .docker-build.yml --verbose --install

script:
  - ./docker-build --name ${DISTRO} --config .docker-build.yml --verbose --build make

env:
  - DISTRO="base/archlinux"
